routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Commentcontroller;
use App\Http\Controllers\TagController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });
Route::get('/', [AuthController::class, 'login'])->name('user.login');
Route::post('/login', [AuthController::class, 'loginpost'])->name('user.loginpost');
Route::get('/registration', [AuthController::class, 'registration'])->name('user.registrate');
Route::post('/registration', [AuthController::class, 'registrationpost'])->name('user.registrationpost');
Route::get('/logout', [AuthController::class,'logout'])->name('user.logout');
Route::resource('post', PostController::class);

Route::group(['middleware' =>'auth'],function() {
    Route::resource('post', PostController::class);
    Route::get('/posts/filter',[PostController::class, 'filter'])->name('post.filter');
    Route::apiResource('comment', Commentcontroller::class);
    Route::get('/tags/{tag}', [TagController::class,'show'])->name('tag.show');
});

resources/views/Tags_Show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card">
                <div class="card-header">
                    <h1>Tag: {{ $tag->name }}</h1>
                </div>
                <div class="card-body">
                    <h2>Posts with this tag:</h2>
                    @if ($posts->count() > 0)
                        <ul class="list-group">
                            @foreach ($posts as $post)
                                <li class="list-group-item"><a href="{{ route('post.show', $post->id) }}">{{ $post->title }}</a></li>
                            @endforeach
                        </ul>
                    @else
                        <p>No posts found with this tag.</p>
                    @endif
                </div>
            </div>
        </div>



    </div>
</body>
</html>

resources/views/comment.blade.php
<div >
    <h2>Comment</h2>
    <div id="app">
        <div v-if="errorMessage" class="alert alert-danger">@{{ errorMessage }}</div>

        <div class="form-group">
            <form id="commentForm" @submit.prevent="submitComment">
              @csrf
              <div class="input-group">
                <input type="text" v-model="newComment" class="form-control" name="comment" id="" aria-describedby="helpId" placeholder="enter your comment">
                <input type="hidden" name="post_id"  v-model="post_id"  class="form-control" value="{{$post_id}}">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <div id="comments" >
            <div v-for="comment in comments" :key="comment.id" class="list-group">
                <div  class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h6 class="mb-1">@{{comment.user.name}}</h6>
                        <small>@{{comment.created_at | formatDate}}</small>
                    </div>
                    @{{ comment.comment }}
                    <div class="d-flex justify-content-end">
                        <button @click="editComment(comment)" v-if="isCommentAuthor(comment)" class="btn btn-outline-primary " style="margin-left: 10px;">Edit</button>
                        <button @click="deleteComment(comment.id)"  v-if="isCommentAuthor(comment)" class="btn btn-outline-danger  " style="margin-left: 10px;" onclick="return confirm('確定要刪除嗎');">Delete</button>
                    </div>
                </div>
            </div>
            <form v-if="editingComment" @submit.prevent="updateComment">
                <div class="input-group">
                    <input type="text" v-model="editedComment" class="form-control" placeholder="edit your comment">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
          </div>

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue-router/3.0.1/vue-router.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vuex/3.0.1/vuex.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.js"></script>
<script>
    new Vue({
        el:'#app',
        data:{
            comments:[],
            newComment:'',
            post_id:'',
            editingComment: false,
            editedComment: '',
            commentToEdit: '',
            errorMessage:'',
        },
        filters:{
            formatDate: function(value){
                const date = new Date(value);
                return date.toLocaleString();
            }
        },
        methods: {
            submitComment:function(){
                axios.post('/comment',{comment: this.newComment, post_id: {{$post_id}}})
                    .then(response =>{
                        console.log(response.data);
                        this.newComment='';
                        this.refreshComments();
                    })
                    .catch(error =>{
                        console.error("ERRRR:: ",error.response.data);
                        this.errorMessage = error.response.data.message;
                    });
            },
            refreshComments:function(){
                axios.get('/comment/{{$post_id}}')
                    .then(response =>{
                        console.log('Response data:', response.data);
                        if(response.data && response.data.length > 0){
                            this.comments=response.data;
                            this.errorMessage='';
                        }
                        else{
                            this.comments = [];
                        }

                    })
                    .catch(error =>{
                        console.error(error.response.data);
                    });
            },
            editComment:function(comment){
                this.editingComment = true;
                this.editedComment = comment.comment;
                this.commentToEdit = comment.id;

            },
            updateComment:function() {
                console.log('Editing comment with comment:', this.editedComment);
                axios.put('/comment/'+this.commentToEdit,{comment: this.editedComment})
                .then(response =>{
                    console.log('Response data:', response.data);
                    this.editedComment = '';
                    this.editingComment = false;
                    this.refreshComments();
                })
                .catch(error =>{
                    console.error(error.response.data);
                    this.errorMessage = error.response.data.message;
                });
            },
            deleteComment:function(commentId){
                console.log(commentId);
                axios.delete('/comment/'+commentId)
                    .then(response => {
                        console.log(response.data);
                        this.refreshComments();
                    })
                    .catch(error =>{
                        console.error(error);
                    })
            },
            isCommentAuthor(comment) {
                const currentUser = {!! json_encode(Auth::user()) !!};
                if (currentUser && comment.user) {
                    return currentUser.name === comment.user.name;
                }
                return false;
            },
        },
        mounted: function() {
            //
            this.refreshComments();
        },
    });

</script>

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".post_row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card">
                <div class="card-header row">
                    <div class="col-md-6">
                        <h1>Blog_CRUD </h1>
                    </div>
                    <div class="col-md-6 d-flex justify-content-end align-items-center">
                        <h2>Welcome {{Auth::user()->name}}</h2>
                        <a name="" id="" class="btn btn-primary" href="{{route('user.logout')}}" role="button">Logout</a>
                        @if(session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    <div class="row py-2">
                        <div class="col-md-3">
                            <a name="CreatePost" id="" class="btn btn-success" href="{{route('post.create')}}" role="button">Add New Post</a>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <form action="{{ route('post.filter') }}"method="get">
                                    <div class="input-group">
                                        <input type="text" name="search" id="" class="form-control" placeholder="Search..." value="{{isset($search) ? $search : ''}}" >
                                        <button type="submit" class="btn btn-primary">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Title</th>
                                <th scope="col">Author</th>
                                <th scope="col">Views</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $post)
                            <tr class="post_row" data-href="{{ route('post.show', $post->id) }}">
                                <th scope="row">{{$post->id}}</th>
                                <td>{{$post->title}}</td>
                                <td>{{$post->user->name}}</td>
                                <td>{{$post->views}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

resources/views/post_edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card">
                <div class="card-header">
                    <h2>Edit Post</h2>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{route('post.update',$post->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("put")
                        <input type="text" class="form-control m-2" name="title" id="" placeholder="title" value="{{$post->title}}">
                        <input type="text" class="form-control m-2" name="Author" id="" placeholder="Author" value="{{$user->name}} " readonly="readonly">
                        <input type="text" class="form-control m-2" name="tags" placeholder="Tags" value="@foreach ($post->tags as $tag){{$tag->name}}@if (!$loop->last), @endif @endforeach">
                        <textarea  class="form-control" name="content" id="" cols="30" rows="10" placeholder="content" >{{$post->content}}</textarea>
                        <img src="/cover/{{$post->image}}"  class="img-responsive" style="max-height:100px; max-width:100px" alt="" sizes="" srcset=""></td>
                        <input class="form-control m-2" name="cover" type="file" id="" >
                        <button type="submit" class="btn btn-success mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/post_show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card">
                <div class="card-header">
                    <div class="row py-2">
                        <div class="col-md-9">
                            <h2 class="">Title: {{ $post->title }}</h2>
                        </div>
                        <div class=" d-flex justify-content-end align-items-center">
                            <a href="{{ route('post.index') }}" class="btn btn-primary" style="margin-left: 10px;">Back to Post List</a>
                            @can('delete-post',$post)
                                <form action="{{ route('post.destroy', $post->id) }}" method="POST">
                                    <button class="btn btn-outline-danger "  style="margin-left: 10px;"onclick="return confirm('確定要刪除嗎');" type="submit">Delete</button>
                                    @csrf
                                    @method('delete')
                                </form>
                            @endcan
                        </div>
                    </div>

                </div>
                <div class="card-body">
                    <p>Author: {{ $post->user->name }}</p>
                    <p>Views: {{ $post->views }}</p>
                    <p>Release Time: {{ $post->created_at->format('Y-m-d H:i:s') }}</p>
                    @foreach ($post->tags as $tag)
                        <a href="{{ route('tag.show', $tag) }}">{{ $tag->name }}</a>
                    @endforeach

                    <hr>
                    <p>content:</p>
                    @can('update-post',$post)
                        <a name="" id="" class="btn btn-outline-primary" href="{{ route('post.edit', $post->id) }}" role="button">Edit</a></td>
                    @endcan
                    <div>{{ $post->content }}</div>
                    <img src="/cover/{{$post->image}}"  class="img-responsive" style="max-height:100px; max-width:100px" alt="" sizes="" srcset="">

                    <hr>
                    @include('comment',['post_id'=>$post->id])

                </div>
            </div>
    </div>
</body>
</html>

resources/views/postcreate.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card">
                <div class="card-header">
                    <h2>Add New Post</h2>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{route('post.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="text" class="form-control m-2" name="title" id="" placeholder="title">
                        <input type="text" class="form-control m-2" name="Author" id="" placeholder="Author" readonly="readonly" value="{{Auth::user()->name}}">
                        <input type="text" class="form-control m-2" name="tags"  placeholder="Tags" >
                        <textarea  class="form-control" name="content" id="" cols="30" rows="10" placeholder="content"></textarea>
                        <input class="form-control m-2" name="cover" type="file" id="">
                        <button type="submit" class="btn btn-success mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>